name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${ACTIONS_DEPLOY_KEY}" > ~/.ssh/gh-pages
          chmod 600 ~/.ssh/gh-pages
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          GIT_SSH_COMMAND="ssh -i ~/.ssh/gh-pages" git push origin gh-pages
